### ISSUE TITLE
demo-complete of part 4. REST APIs did not work until replaced 'let' with 'var'

### ISSUE THREAD

**Issue by freejavaster** [NZMSA/2016-Module-2#3]
demo-complete of part 4. REST APIs did not work,
until I replaced  
`let scores = data[0].scores;`
with
`var scores = data[0].scores;`

in basic.js line 116.

**Comment by brianoctan** [comment]
Hi there

"let" is an ES6+ feature that some browsers might not have fully implemented.

Ensure you are on the latest browser version and are using a compatible browser 
- the latest versions of Edge or Chrome will work

The ES6+ compatibility list can be found here: http://kangax.github.io/compat-table/es6/#test-let

**Comment by techno246** [comment]
Will update the example code to resolve this compatibility issue!
